apiVersion: v1
kind: Service
metadata:
  name: {{ AGENT_NAME }}-svc
  namespace: {{ NAMESPACE }}
spec:
  selector:
    app: {{ AGENT_NAME }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
